config/routes.rb
Site::Application.routes.draw do

  resources :points

  resources :locations_users

  resources :locations_locationsets

  resources :locationsets_users

  resources :loactionsets_users

  resources :groups_locations

  resources :locationsets

  resources :groups_users

  resources :userparams

  resources :synthinstances

  resources :audiofiles

  resources :synths

  resources :groups

  match '/users/device_update/:id' => "users#update_2"

  match '/users/device_login' => "users#device_login"

  match '/users/device_logout/:id' => "users#device_logout"

  match '/users/device_edit/:id' => "users#device_edit"

  match '/users/device_create' => "users#device_create"

  match '/users/device_update_params/:id' => "users#device_update_params"

  match '/users/device_enter_location/:id' => "users#device_enter_location"

  match '/users/device_exit_location/:id' => "users#device_exit_location"

  match '/locations/device_create' => "locations#device_create"

  resources :users

  resources :locations

  get "home/index"

  match "/locations/download" => "locations#download", :as => :download

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :groups
  has_one :synth
  has_one :userparam
  has_and_belongs_to_many :locationsets

  validates_uniqueness_of :name
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def device_create
    @user = User.new(params[:user])
    data = {"active" => true, "name" => params[:name], "password" => params[:password], "latitude" => params[:latitude], "longitude" => params[:longitude], "synth_id" => 1, "audio_id" => 1, "ip" => request.remote_ip, "synth_id" => 1, "audio_id" => 1}
    @user.update_attributes(data)
    respond_to do |format|
      if @user.save
        #create a userparam for this
        #@userparam = Userparam.new_by_user_id(@user.id)
        @userparam = Userparam.new
        @userparam.user_id = @user.id
        @userparam.save
        format.html { render :text => @user.id }
        format.xml { render :text => @user.id }
      else
        format.html { render :text => 0 }
        format.xml  { render :text => 0 }
      end
    end
  end

  def device_login
    #check if the username and password match. return the id if yes. 0 if no.
    #set that @user as active
    @user = User.find_by_name(params[:name])
    response = ""
    unless @user.nil?
      if @user.password == params[:password]
        data = {"active" => true, "ip" => request.remote_ip}
        @user.update_attributes(data)
        response = @user.id
      else
        response = 0
      end
    Location.aggregate_params(@user)
    end
    respond_to do |format|
      format.html { render :text => response }
      format.xml { render :text => response }
    end
  end

  def device_logout
    @user = User.find(params[:id])
    data = {"active" => false, "ip" => request.remote_ip}
    @user.update_attributes(data)
    @user.locations = []
    @user.save
    respond_to do |format|
      format.html { render :text => 0 }
      format.xml  { render :text => 0 }
    end
  end

  def device_edit
    @user = User.find(params[:id])
    data = {"name" => params[:name], "password" => params[:password], "ip" => request.remote_ip}

    respond_to do |format|
      if @user.update_attributes(data)
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def device_update_params
    @param = Userparam.find_by_user_id(params[:id])
    if (params[:param_1] != nil)
      @param.value_1 = params[:param_1]
    end
    if (params[:param_2] != nil)
      @param.value_2 = params[:param_2]
    end
    if (params[:param_3] != nil)
      @param.value_3 = params[:param_3]
    end
    @param.save
    Location.aggregate_params(User.find(params[:id]))
    respond_to do |format|
      format.html { render :text => "cool story" }
      format.xml { render :text => "cool story" }
    end
  end

  def device_enter_location
    @location = Location.find_by_name(params[:location_name])
    
    @location.user_ids = @location.user_ids + [params[:id]]
    logger.debug("ids = #{@location.user_ids.inspect}")
    @location.save
    Location.aggregate_params_location(@location)
    respond_to do |format|
      format.html { render :text => "cool story" }
      format.xml { render :text => "cool story" }
    end
  end

  def device_exit_location
    @location = Location.find_by_name(params[:location_name])
    @location.users.delete(User.find(params[:id]))
    Location.aggregate_params_location(@location)
    respond_to do |format|
      format.html { render :text => "cool story" }
      format.xml { render :text => "cool story" }
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/device_update/1
  # PUT /users/device_update/1.xml
  def update_2
    @user = User.find(params[:id])
    data = {"latitude" => params[:latitude], "longitude" => params[:longitude], "ip" => request.remote_ip}
    
    respond_to do |format|
      if @user.update_attributes(data)
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :synth_id %><br />
    <%= f.text_field :synth_id %>
  </div>
  <div class="field">
    <%= f.label :audio_id %><br />
    <%= f.text_field :audio_id %>
  </div>
  <div class="field">
    <%= f.label :group_ids %><br />
    <%= f.collection_select :group_ids, Group.all, :id, :name, {}, { :multiple => true, :selected => 'user[group_ids]', :name => 'user[group_ids][]' } %>
  </div>
  <div class="field">
    <%= f.label :locationset_ids %><br />
    <%= f.collection_select :locationset_ids, Locationset.all, :id, :name, {}, { :multiple => true, :selected => 'user[locationset_ids]', :name => 'user[locationset_ids][]' } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>IP</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Active</th>
    <th>Synth</th>
    <th>Audio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.ip %></td>
    <td><%= user.latitude %></td>
    <td><%= user.longitude %></td>
    <td><%= user.active %></td>
    <td><%= link_to user.synth_id, synth_path(user.synth_id) %></td>
    <td><%= link_to user.audio_id, audiofile_path(user.audio_id) %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Ip:</b>
  <%= @user.ip %>
</p>

<p>
  <b>Latitude:</b>
  <%= @user.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @user.longitude %>
</p>

<p>
  <b>Active:</b>
  <%= @user.active %>
</p>

<p>
  <b>Synth:</b>
  <%= @user.synth_id %>
</p>

<p>
  <b>Audio:</b>
  <%= @user.audio_id %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>