config/routes.rb
Site::Application.routes.draw do

  resources :points

  resources :locations_users

  resources :locations_locationsets

  resources :locationsets_users

  resources :loactionsets_users

  resources :groups_locations

  resources :locationsets

  resources :groups_users

  resources :userparams

  resources :synthinstances

  resources :audiofiles

  resources :synths

  resources :groups

  match '/users/device_update/:id' => "users#update_2"

  match '/users/device_login' => "users#device_login"

  match '/users/device_logout/:id' => "users#device_logout"

  match '/users/device_edit/:id' => "users#device_edit"

  match '/users/device_create' => "users#device_create"

  match '/users/device_update_params/:id' => "users#device_update_params"

  match '/users/device_enter_location/:id' => "users#device_enter_location"

  match '/users/device_exit_location/:id' => "users#device_exit_location"

  match '/locations/device_create' => "locations#device_create"

  resources :users

  resources :locations

  get "home/index"

  match "/locations/download" => "locations#download", :as => :download

  root :to => "home#index"

end

app/models/audiofile.rb
class Audiofile < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :locations
  has_one :synthinstance
  has_one :synth
end

app/models/groups_location.rb
class GroupsLocation < ActiveRecord::Base
end

app/models/groups_user.rb
class GroupsUser < ActiveRecord::Base
end

app/models/location.rb
require 'rubygems'
require 'osc'
include OSC

class Location < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :locationsets
  has_many :points

  
  @c = OSC::UDPSocket.new
  validates_uniqueness_of :name
  #call me when a user enters/exits the location or changes params
  def self.aggregate_params(user)
    
    @locations = user.locations.readonly(false)
    @locations.each do |location|
      aggregate_params_location(location)
    end
  end

  def self.aggregate_params_location(location)
    users = User.find(:all, :conditions => {:active => true, :id => location.user_ids})
    params = Userparam.where(:user_id => users)
    location.param_1 = params.average("value_1")
    location.param_2 = params.sum("value_2")
    location.param_3 = Math.log(params.sum("value_3")+1)
    #apply mathematical functions to the params.
    location.save
    users.each do |user|
      m = Message.new('/Server', 'sfff', location.name, location.param_1, location.param_2, location.param_3)
      puts "#{@c.inspect}"
      puts "#{m.inspect}"
      @c.send m, 0, user.ip, 8000
    end
  end

end

app/models/locations_user.rb
class LocationsUser < ActiveRecord::Base
end

app/models/locationset.rb
class Locationset < ActiveRecord::Base
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :users
end

app/models/locationsets_user.rb
class LocationsetsUser < ActiveRecord::Base
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :location
end

app/models/synth.rb
class Synth < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/synthinstance.rb
class Synthinstance < ActiveRecord::Base
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :groups
  has_one :synth
  has_one :userparam
  has_and_belongs_to_many :locationsets

  validates_uniqueness_of :name
end

app/models/userparam.rb
class Userparam < ActiveRecord::Base
  belongs_to :user
end

app/controllers/groups_users_controller.rb
class GroupsUsersController < ApplicationController
  # GET /groups_users
  # GET /groups_users.xml
  def index
    @groups_users = GroupsUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups_users }
    end
  end

  # GET /groups_users/1
  # GET /groups_users/1.xml
  def show
    @groups_user = GroupsUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @groups_user }
    end
  end

  # GET /groups_users/new
  # GET /groups_users/new.xml
  def new
    @groups_user = GroupsUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @groups_user }
    end
  end

  # GET /groups_users/1/edit
  def edit
    @groups_user = GroupsUser.find(params[:id])
  end

  # POST /groups_users
  # POST /groups_users.xml
  def create
    @groups_user = GroupsUser.new(params[:groups_user])

    respond_to do |format|
      if @groups_user.save
        format.html { redirect_to(@groups_user, :notice => 'Groups user was successfully created.') }
        format.xml  { render :xml => @groups_user, :status => :created, :location => @groups_user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @groups_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /groups_users/1
  # PUT /groups_users/1.xml
  def update
    @groups_user = GroupsUser.find(params[:id])

    respond_to do |format|
      if @groups_user.update_attributes(params[:groups_user])
        format.html { redirect_to(@groups_user, :notice => 'Groups user was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @groups_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /groups_users/1
  # DELETE /groups_users/1.xml
  def destroy
    @groups_user = GroupsUser.find(params[:id])
    @groups_user.destroy

    respond_to do |format|
      format.html { redirect_to(groups_users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/audiofiles_helper.rb
module AudiofilesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/groups_users_helper.rb
module GroupsUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/synths_helper.rb
module SynthsHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups_users/_form.html.erb
<%= form_for(@groups_user) do |f| %>
  <% if @groups_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@groups_user.errors.count, "error") %> prohibited this groups_user from being saved:</h2>

      <ul>
      <% @groups_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.text_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups_users/edit.html.erb
<h1>Editing groups_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @groups_user %> |
<%= link_to 'Back', groups_users_path %>

app/views/groups_users/index.html.erb
<h1>Listing groups_users</h1>

<table>
  <tr>
    <th>Group</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups_users.each do |groups_user| %>
  <tr>
    <td><%= groups_user.group_id %></td>
    <td><%= groups_user.user_id %></td>
    <td><%= link_to 'Show', groups_user %></td>
    <td><%= link_to 'Edit', edit_groups_user_path(groups_user) %></td>
    <td><%= link_to 'Destroy', groups_user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Groups user', new_groups_user_path %>

app/views/groups_users/new.html.erb
<h1>New groups_user</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_users_path %>

app/views/groups_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group:</b>
  <%= @groups_user.group_id %>
</p>

<p>
  <b>User:</b>
  <%= @groups_user.user_id %>
</p>


<%= link_to 'Edit', edit_groups_user_path(@groups_user) %> |
<%= link_to 'Back', groups_users_path %>