config/routes.rb
Site::Application.routes.draw do

  resources :points

  resources :locations_users

  resources :locations_locationsets

  resources :locationsets_users

  resources :loactionsets_users

  resources :groups_locations

  resources :locationsets

  resources :groups_users

  resources :userparams

  resources :synthinstances

  resources :audiofiles

  resources :synths

  resources :groups

  match '/users/device_update/:id' => "users#update_2"

  match '/users/device_login' => "users#device_login"

  match '/users/device_logout/:id' => "users#device_logout"

  match '/users/device_edit/:id' => "users#device_edit"

  match '/users/device_create' => "users#device_create"

  match '/users/device_update_params/:id' => "users#device_update_params"

  match '/users/device_enter_location/:id' => "users#device_enter_location"

  match '/users/device_exit_location/:id' => "users#device_exit_location"

  match '/locations/device_create' => "locations#device_create"

  resources :users

  resources :locations

  get "home/index"

  match "/locations/download" => "locations#download", :as => :download

  root :to => "home#index"

end

app/models/audiofile.rb
class Audiofile < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :locations
  has_one :synthinstance
  has_one :synth
end

app/models/groups_location.rb
class GroupsLocation < ActiveRecord::Base
end

app/models/groups_user.rb
class GroupsUser < ActiveRecord::Base
end

app/models/location.rb
require 'rubygems'
require 'osc'
include OSC

class Location < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :locationsets
  has_many :points

  
  @c = OSC::UDPSocket.new
  validates_uniqueness_of :name
  #call me when a user enters/exits the location or changes params
  def self.aggregate_params(user)
    
    @locations = user.locations.readonly(false)
    @locations.each do |location|
      aggregate_params_location(location)
    end
  end

  def self.aggregate_params_location(location)
    users = User.find(:all, :conditions => {:active => true, :id => location.user_ids})
    params = Userparam.where(:user_id => users)
    location.param_1 = params.average("value_1")
    location.param_2 = params.sum("value_2")
    location.param_3 = Math.log(params.sum("value_3")+1)
    #apply mathematical functions to the params.
    location.save
    users.each do |user|
      m = Message.new('/Server', 'sfff', location.name, location.param_1, location.param_2, location.param_3)
      puts "#{@c.inspect}"
      puts "#{m.inspect}"
      @c.send m, 0, user.ip, 8000
    end
  end

end

app/models/locations_user.rb
class LocationsUser < ActiveRecord::Base
end

app/models/locationset.rb
class Locationset < ActiveRecord::Base
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :users
end

app/models/locationsets_user.rb
class LocationsetsUser < ActiveRecord::Base
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :location
end

app/models/synth.rb
class Synth < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/synthinstance.rb
class Synthinstance < ActiveRecord::Base
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :locations
  has_and_belongs_to_many :groups
  has_one :synth
  has_one :userparam
  has_and_belongs_to_many :locationsets

  validates_uniqueness_of :name
end

app/models/userparam.rb
class Userparam < ActiveRecord::Base
  belongs_to :user
end

app/controllers/locationsets_controller.rb
class LocationsetsController < ApplicationController
  # GET /locationsets
  # GET /locationsets.xml
  def index
    @locationsets = Locationset.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locationsets }
    end
  end

  # GET /locationsets/1
  # GET /locationsets/1.xml
  def show
    @locationset = Locationset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @locationset }
    end
  end

  # GET /locationsets/new
  # GET /locationsets/new.xml
  def new
    @locationset = Locationset.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @locationset }
    end
  end

  # GET /locationsets/1/edit
  def edit
    @locationset = Locationset.find(params[:id])
  end

  # POST /locationsets
  # POST /locationsets.xml
  def create
    @locationset = Locationset.new(params[:locationset])

    respond_to do |format|
      if @locationset.save
        format.html { redirect_to(@locationset, :notice => 'Locationset was successfully created.') }
        format.xml  { render :xml => @locationset, :status => :created, :location => @locationset }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @locationset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locationsets/1
  # PUT /locationsets/1.xml
  def update
    @locationset = Locationset.find(params[:id])

    respond_to do |format|
      if @locationset.update_attributes(params[:locationset])
        format.html { redirect_to(@locationset, :notice => 'Locationset was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @locationset.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locationsets/1
  # DELETE /locationsets/1.xml
  def destroy
    @locationset = Locationset.find(params[:id])
    @locationset.destroy

    respond_to do |format|
      format.html { redirect_to(locationsets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/audiofiles_helper.rb
module AudiofilesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/locationsets_helper.rb
module LocationsetsHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/synths_helper.rb
module SynthsHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/locationsets/_form.html.erb
<%= form_for(@locationset) do |f| %>
  <% if @locationset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locationset.errors.count, "error") %> prohibited this locationset from being saved:</h2>

      <ul>
      <% @locationset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location_ids %><br />
    <%= f.collection_select :location_ids, Location.all, :id, :name, {}, { :multiple => true, :selected => 'locationset[location_ids]', :name => 'locationset[location_ids][]' } %>
  </div>
  <div class="field">
    <%= f.label :user_ids %><br />
    <%= f.collection_select :user_ids, User.all, :id, :name, {}, { :multiple => true, :selected => 'locationset[user_ids]', :name => 'locationset[user_ids][]' } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locationsets/edit.html.erb
<h1>Editing locationset</h1>

<%= render 'form' %>

<%= link_to 'Show', @locationset %> |
<%= link_to 'Back', locationsets_path %>

app/views/locationsets/index.html.erb
<h1>Listing locationsets</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locationsets.each do |locationset| %>
  <tr>
    <td><%= locationset.name %></td>
    <td><%= link_to 'Show', locationset %></td>
    <td><%= link_to 'Edit', edit_locationset_path(locationset) %></td>
    <td><%= link_to 'Destroy', locationset, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Locationset', new_locationset_path %>

app/views/locationsets/new.html.erb
<h1>New locationset</h1>

<%= render 'form' %>

<%= link_to 'Back', locationsets_path %>

app/views/locationsets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @locationset.name %>
</p>


<%= link_to 'Edit', edit_locationset_path(@locationset) %> |
<%= link_to 'Back', locationsets_path %>